### PR TITLE
Creation of header and headline

### PR DESCRIPTION
**Pull request by mikemtzp**
## Creation of header and headline

For this portfolio feature I:

### HTML
- Created a .html file.
- Elaborated an approximate structure based on Figma's template 2.
- Created a `header` section `nav` section and divided it into a bigger `div` and a `nav`.
- Nested the elements `p` and `li` from an `ul` in order to manipulate them later in the CSS.
- Created a new `section` for the headline.
- Created 3 different `divs` to hold in the next sections: social media icons, my presentation, and an image.

### CSS
- Created a stylesheet file. 
- Elaborated an approximate design based on Figma's template 2.
- Used the `*` symbol to establish some universal parameters in the stylesheet.
- Used Flexbox to distribute the position of all the elements in the HTML.
- Customize each class as it was needed.
- Used when needed nested Flexbox.

#### *All the readme.md and linters tests were correctly set up.

### CODE REVIEW

**Review by koomekevo — CHANGES_REQUESTED** [review]
Hi @mikemtzp 

 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Your README and Pull Request are descriptive.
- [ ] Your project has no linter errors.  

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly adhere to the Figma template mobile design. The below screenshot is your design. 

Wrong Design

The below screenshot is the correct design. 

Correct Design

- [ ] Kindly modify the header to display the hamburger icon which displays the navigation links when clicked. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikemtzp** [comment]
Thanks for the review! @koomekevo

Do I need to make this hamburger button clickable in this step in the project?
Or it's ok if I just display the button?

**Comment by koomekevo** [comment]
> Thanks for the review! @koomekevo
> 
> Do I need to make this hamburger button clickable in this step in the project? Or it's ok if I just display the button?

@mikemtzp No at this stage you do not need to implement the functionality of the hamburger icon

**Comment by mikemtzp** [comment]
Hi @koomekevo 

I've finally finished all the changes so it can be displayed for mobile. It was a big challenge for me but here it is.
Thank you very much!

image

**Review by zainsadaqat — APPROVED** [review]
# Hello @mikemtzp 😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

[Optional]
You can remove this status bar as it was not the requirement. In Figma design, it was just to show that it's mobile design. 😄 
Screen Shot 2022-04-22 at 6 17 33 AM


## Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikemtzp** [comment]
Thanks a lot @zainsadaqat!

At least now I know how to create a mobile status bar.😆

**Pull request merged**
